name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Gradle command
      uses: Raul6469/android-gradle-action@2.0.0
      with:
        # The gradle command you wish to run (required)
        # Here, `./gradlew test` will be run
        script: test
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 6.5
        arguments: build
        build-root-directory: ./android
